# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import synthesis_pb2 as synthesis__pb2
from . import task_pb2 as task__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in synthesis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartSpeechStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
                '/smartspeech.synthesis.v1.SmartSpeech/Synthesize',
                request_serializer=synthesis__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=synthesis__pb2.SynthesisResponse.FromString,
                _registered_method=True)
        self.AsyncSynthesize = channel.unary_unary(
                '/smartspeech.synthesis.v1.SmartSpeech/AsyncSynthesize',
                request_serializer=synthesis__pb2.AsyncSynthesisRequest.SerializeToString,
                response_deserializer=task__pb2.Task.FromString,
                _registered_method=True)


class SmartSpeechServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncSynthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartSpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=synthesis__pb2.SynthesisRequest.FromString,
                    response_serializer=synthesis__pb2.SynthesisResponse.SerializeToString,
            ),
            'AsyncSynthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncSynthesize,
                    request_deserializer=synthesis__pb2.AsyncSynthesisRequest.FromString,
                    response_serializer=task__pb2.Task.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartspeech.synthesis.v1.SmartSpeech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartspeech.synthesis.v1.SmartSpeech', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartSpeech(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/smartspeech.synthesis.v1.SmartSpeech/Synthesize',
            synthesis__pb2.SynthesisRequest.SerializeToString,
            synthesis__pb2.SynthesisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncSynthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartspeech.synthesis.v1.SmartSpeech/AsyncSynthesize',
            synthesis__pb2.AsyncSynthesisRequest.SerializeToString,
            task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
